version: '3.8'

services:
  app:
    build: .
    container_name: fos-core
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fos-core-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_VIRTUAL_HOST: vhost
      SPRING_RABBITMQ_USERNAME: rab
      SPRING_RABBITMQ_PASSWORD: 1234
      SPRING_RABBITMQ_PORT: 5672
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: fos-core-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fos-core-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rab
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_DEFAULT_USER_TAGS: administrator
      RABBITMQ_DEFAULT_PERMISSIONS: ".* .* .*"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq￼
    ports:
      - "5672:5672"
      - "15672:15672"
