#version: '3.8'
#
#services:
#  core:
#    build: .
#    image: fos-core-image
#    container_name: fos-core
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fos-core-db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: password
#
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_RABBITMQ_VIRTUAL_HOST: vhost
#      SPRING_RABBITMQ_USERNAME: rab
#      SPRING_RABBITMQ_PASSWORD: 1234
#      SPRING_RABBITMQ_PORT: 5672
#
#      STRIPE_API_KEY: pk_test_51QEqbRLpw8bYPSLySTjaEWbMfx1YsX30zlK3bprzDi8QAMM4CpqvZq9npLF1KviVmaUY82wicPNqHhX2F4s3VTdz00Acy35Wcx
#      STRIPE_API_SECRET_KEY: sk_test_51QEqbRLpw8bYPSLy6e8b7q636ScJIPrQaqnMbduJiihJLlO0CBBVcJqzv9F7Yi3k5bOMGYFRH2ypB7VlvRESmctD00FIoFCKuN
#
#      JWT_ISSUER-URI: http://localhost:9000
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#      - rabbitmq
#    networks:
#      - fos-network
#    restart: on-failure
#
##  postgres:
##    image: postgres:15
##    container_name: fos-core-postgres
##    environment:
##      POSTGRES_USER: postgres
##      POSTGRES_PASSWORD: password
##      POSTGRES_DB: fos-core-db
##    ports:
##      - "5432:5432"
##    volumes:
##      - postgres-data:/var/lib/postgresql/data
##    networks:
##      - fos-network
##
##  rabbitmq:
##    image: rabbitmq:latest
##    container_name: rabbitmq
##    hostname: rabbitmq
##    restart: on-failure
##    environment:
##      RABBITMQ_DEFAULT_USER: rab
##      RABBITMQ_DEFAULT_PASS: 1234
##      RABBITMQ_DEFAULT_VHOST: vhost
##      RABBITMQ_DEFAULT_USER_TAGS: administrator
##      RABBITMQ_DEFAULT_PERMISSIONS: ".* .* .*"
##    volumes:
##      - rabbitmq:/var/lib/rabbitmq￼
##    ports:
##      - "5672:5672"
##      - "15672:15672"
##    networks:
##      - fos-network
##
##volumes:
##  postgres-data:
##  rabbitmq:
##
##networks:
##  fos-network:
##    name: fos-network