name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t food-ordering-system-app .
          docker tag food-ordering-system-app:latest 615299745224.dkr.ecr.us-east-1.amazonaws.com/food-ordering-system-app:latest

      - name: Push Docker image to ECR
        run: |
          docker push 615299745224.dkr.ecr.us-east-1.amazonaws.com/food-ordering-system-app:latest

      - name: Deploy to ECS
        uses: aws-actions/ecs-deploy@v1
        with:
          cluster: my-cluster
          service: my-service
          task-definition: my-task-definition
          image: 615299745224.dkr.ecr.us-east-1.amazonaws.com/food-ordering-system-app:latest
          wait-for-service-stability: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
